### PR TITLE
Add bhyve/set command to accept direct/raw command

### PR DESCRIPTION
**Pull request by jimtng**
Adds `bhyve/set` command. The content of the command gets passed directly to oClient.send(). This will open up the possibility to directly communicate with the orbit server

### CODE REVIEW

**Comment by jimtng** [comment]
I'm not sure if bhyve/set is a good topic name. Do you think bhyve/command would be better?

**Comment by billchurch** [comment]
I like the idea of this, but worried that it could potentially lead to abuse. I don't claim that my code is bullet-proof but I usually like to know what is being sent to another environment when acting as a proxy. 

Not shutting the door on this feature, just need to consider it a little more.

**Comment by billchurch** [comment]
@jimtng, do you have an example of a raw command you would send for a use case?

**Comment by jimtng** [comment]
I used it to manually turn on / off the tap itself. It was a crucial feature for me so I was using my fork all this time because of it. I no longer use bhyve now though, as you know.

**Pull request closed without merging**
